### ISSUE TITLE
解码有点问题-base64

### ISSUE THREAD

**Issue by junfei** [navyxie/yeepay#1]
我调parseReturn进行解码的时候会报这个错
Error: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag
  at Error (native)
  at Object.decrypt (/Users/air/heroes/node_modules/yeepay/node_modules/ursa/lib/ursa.js:359:33)
  at Object.decryptKey (/Users/air/heroes/node_modules/yeepay/lib/crypto.js:196:13)
  at yeePay.decryptKey (/Users/air/heroes/node_modules/yeepay/lib/yeepay.js:162:22)
  at yeePay.parseReturn (/Users/air/heroes/node_modules/yeepay/lib/yeepay.js:226:21)

看了一下是这行代码
代码行-----pem.decrypt(key, 'binary', 'utf8', ursa.RSA_PKCS1_PADDING)

然后我跳过这个函数拿aes私钥的函数,直接拿aes秘钥进行这个函数的调用
yeepay.js:
var jsonStr = this.deEAS(data,easKey);
继续跑下去发现后面的解码在这行会报这个错
代码行-----plainChunks.push(decipher.final(clearEncoding));

Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
  at Error (native)
  at Decipheriv.Cipher.final (crypto.js:202:26)
  at decrypt (/Users/air/heroes/node_modules/yeepay/lib/crypto.js:112:44)
  at Object.deEAS (/Users/air/heroes/node_modules/yeepay/lib/crypto.js:137:9)
  at yeePay.deEAS (/Users/air/heroes/node_modules/yeepay/lib/yeepay.js:170:22)
  at yeePay.parseReturn (/Users/air/heroes/node_modules/yeepay/lib/yeepay.js:228:22)

我对比调试了一下java版本的易宝接入,发现base64解码和java的对不上,不知道是不是我引用的base64有问题,找了几个版本还是这样,没办法用了以下这种方式

/**
- 解密 EAS
  *
- @param string data
- @param string key
- @return string
  */
  function deEAS(data,key){
  data = decodeURIComponent(data);
  var encryptdata = new Buffer(data, 'base64').toString('binary');
  return decrypt(encryptdata,key,'aes-128-ecb','utf8','binary','');
  }
  在这里记录一下,如果有人遇到类似的问题可以参考下

**Comment by navyxie** [comment]
谢谢！
